# Generated by Django 2.2.5 on 2019-09-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tconst', models.IntegerField(unique=True)),
                ('title_type', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_title', models.CharField(blank=True, max_length=250, null=True)),
                ('original_title', models.CharField(blank=True, max_length=250, null=True)),
                ('is_adult', models.BooleanField(default=False)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('runtime_minutes', models.IntegerField()),
                ('genres', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
