# Generated by Django 2.2.5 on 2019-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='tconst',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
