# Generated by Django 2.2.5 on 2019-09-18 19:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('title_type', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_title', models.CharField(blank=True, max_length=500, null=True)),
                ('original_title', models.CharField(blank=True, max_length=500, null=True)),
                ('is_adult', models.BooleanField(default=False)),
                ('start_year', models.CharField(blank=True, max_length=250, null=True)),
                ('end_year', models.CharField(blank=True, max_length=250, null=True)),
                ('runtime_minutes', models.CharField(blank=True, max_length=250, null=True)),
                ('genres', models.CharField(blank=True, max_length=250, null=True)),
                ('cache_average_rating', models.IntegerField(default=0)),
                ('cache_num_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_search', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'db_table': 'films',
            },
        ),
        migrations.AddIndex(
            model_name='film',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search'], name='films_content_59eacd_gin'),
        ),
    ]
