# Generated by Django 2.2.5 on 2019-09-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190917_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='runtime_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
