# Generated by Django 2.2.5 on 2019-09-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190917_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='tconst',
            field=models.IntegerField(db_index=True, editable=False, unique=True),
        ),
    ]
