version: '3'
services:
  postgres:
    restart: always
    image: postgres:10.1-alpine
    container_name: "database"
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  web:
    restart: always
    build: ./web
    image: web
    expose:
      - "8000"
    links:
      - postgres:postgres
    env_file: .env
    command: /usr/local/bin/gunicorn config.wsgi:application -w 2 --threads=2 --worker-connections=100 -b :8000
    volumes:
      - web-app:/usr/src/app
      - web-static:/usr/src/app/static
    ports:
      - "8000:8000"
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "5000:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web
volumes:
  pgdata:
  web-static:
  web-app: