version: '3.7'

services:
  database:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python manage.py migrate && make runserver
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - database

volumes:
  postgres_data: