# Generated by Django 2.2.5 on 2019-09-18 09:42
from django.utils import timezone
from django.db import migrations
from django.contrib.auth.models import User


def load_first_user(apps, schema_editor):
    User(
        id=1,
        password='pbkdf2_sha256$150000$aBO6WDZXjCpM$ySqyJR9RG0GRQnjvPoB1q00Jbfb4GKAVROatEoUMSIU=',
        is_superuser=True,
        username='admin',
        email='admin@gmail.com',
        is_staff=True,
        is_active=True,
        date_joined=timezone.now(),
    ).save()


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(load_first_user)]
