# Generated by Django 2.2.5 on 2019-09-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [('movies', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.IntegerField(db_index=True, editable=False, unique=True)),
                ('title_type', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_title', models.CharField(blank=True, max_length=500, null=True)),
                ('original_title', models.CharField(blank=True, max_length=500, null=True)),
                ('is_adult', models.BooleanField(default=False)),
                ('start_year', models.CharField(blank=True, max_length=250, null=True)),
                ('end_year', models.CharField(blank=True, max_length=250, null=True)),
                ('runtime_minutes', models.CharField(blank=True, max_length=250, null=True)),
                ('genres', models.CharField(blank=True, max_length=250, null=True)),
                ('cache_average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cache_num_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'films', 'ordering': ['-cache_num_votes', '-cache_average_rating']},
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.IntegerField(db_index=True, editable=False, unique=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_votes', models.IntegerField(default=0)),
            ],
            options={'db_table': 'ratings'},
        ),
    ]
