# Generated by Django 2.2.5 on 2019-09-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_film_rating'),
    ]

    migration = '''
        ALTER TABLE "public"."films" ALTER COLUMN "cache_average_rating" SET DEFAULT '0';
        ALTER TABLE "public"."films" ALTER COLUMN "cache_num_votes" SET DEFAULT '0';
        ALTER TABLE "public"."films" ALTER COLUMN "created_at" SET DEFAULT NOW();
        ALTER TABLE "public"."films" ALTER COLUMN "updated_at" SET DEFAULT NOW();
    '''
    operations = [
        migrations.RunSQL(migration)
    ]
