# Generated by Django 2.2.5 on 2019-09-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190918_1937'),
    ]

    migration = '''
        ALTER TABLE "public"."films" ALTER COLUMN "cache_average_rating" SET DEFAULT '0';
        ALTER TABLE "public"."films" ALTER COLUMN "cache_num_votes" SET DEFAULT '0';
        ALTER TABLE "public"."films" ALTER COLUMN "created_at" SET DEFAULT NOW();
        ALTER TABLE "public"."films" ALTER COLUMN "updated_at" SET DEFAULT NOW();

        CREATE TRIGGER content_search_update BEFORE INSERT OR UPDATE
        ON films FOR EACH ROW EXECUTE PROCEDURE
        tsvector_update_trigger(content_search, 'pg_catalog.english', original_title, original_title);
        UPDATE films set ID = ID;
    '''

    reverse_migration = '''
        DROP TRIGGER content_search ON films;
    '''

    operations = [
        migrations.RunSQL(migration, reverse_migration)
    ]