# Generated by Django 2.2.5 on 2019-09-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190918_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-cache_num_votes', '-cache_average_rating']},
        ),
        migrations.AlterField(
            model_name='film',
            name='cache_average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
