# Generated by Django 2.2.5 on 2019-09-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190919_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.IntegerField(db_index=True, editable=False, unique=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_votes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.AlterField(
            model_name='film',
            name='tconst',
            field=models.IntegerField(db_index=True, editable=False, unique=True),
        ),
    ]
